language: php 
php: 
 - 5.3
 - 5.4
 - 5.5






env:
 - TESTDB=MYSQL
    
matrix:
  exclude:
    - php: 5.4
      env: TESTDB=PGSQL

before_script:
 - ./tests/travis/before_script ~/builds/ss
 - cd ~/builds/ss

script: 
 - php framework/cli-script.php dev/tests/module/cms

branches:
  except:
    # - 2.1
    # - 2.2

notifications:
  irc:
    channels:
     # - "irc.freenode.org#silverstripe"
